# Generated by Django 5.2.17 on 2026-08-11 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('starter', 'Starter (£2.50/staff)'), ('professional', 'Professional (£5.00/staff)'), ('enterprise', 'Enterprise (£8.00-10.00/staff)'), ('company_small', 'Small Company (£99/mo)'), ('company_medium', 'Medium Company (£299/mo)'), ('company_large', 'Large Company (£499-699/mo)')], default='professional', max_length=50)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_staff_limit', models.PositiveIntegerField(default=10)),
                ('is_whitelabel_enabled', models.BooleanField(default=False)),
                ('setup_fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='description',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='shiftapplication',
            old_name='applied_at',
            new_name='signature_timestamp',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='document',
            name='digital_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified / Approved'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Document Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='shiftapplication',
            name='policy_signed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('sia_licence', 'SIA Licence'), ('proof_of_address', 'Proof of Address'), ('passport_id', 'Passport / ID'), ('right_to_work', 'Right to Work'), ('other', 'Other Certification')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='incident',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='officer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shiftlog',
            name='type',
            field=models.CharField(choices=[('checkin', 'Check-In'), ('checkout', 'Check-Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shiftlog',
            name='within_boundary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('supervisor', 'Supervisor'), ('officer', 'Officer / Staff')], default='officer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_officers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='shiftapplication',
            unique_together={('shift', 'officer')},
        ),
        migrations.AddField(
            model_name='shift',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.company'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shift')),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
