# core/views.py
from rest_framework import status, permissions, generics, serializers
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken
from django.shortcuts import get_object_or_404
from django.core.signing import TimestampSigner, BadSignature, SignatureExpired
from drf_spectacular.utils import extend_schema, OpenApiParameter, inline_serializer

from .models import User, Shift, ShiftApplication, ShiftLog, LiveLocation, Incident, Report, Message
from .serializers import (
    UserSerializer, ShiftSerializer, ShiftApplicationSerializer,
    IncidentSerializer, ReportSerializer, MessageSerializer, LoginSerializer, RegisterOfficerSerializer,
    DocumentSerializer, InvoiceSerializer, CompanySerializer
)
from core.permissions import IsSuperAdmin, IsSupervisor, IsOfficer
from .utils import calculate_haversine_distance
from django.utils import timezone
from datetime import timedelta
from typing import cast
from .models import User,Document, Invoice, Company
import uuid

signer = TimestampSigner()

# ==========================================
# 1. AUTHENTICATION MODULE (3 APIs)
# ==========================================

@extend_schema(
    summary="User Login",
    description="Authenticate any user and return JWT tokens",
    request=LoginSerializer,  # <--- Tells Swagger to display email & password fields!
)
@api_view(['POST'])
@permission_classes([permissions.AllowAny])
def login_view(request):
    email = request.data.get('email')
    password = request.data.get('password')

    user = User.objects.filter(email=email).first()
    if not user or not user.check_password(password):
        return Response({'error': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)

    if user.status != User.Status.ACTIVE:
        return Response({'error': f'Account is {user.status}. Access denied.'}, status=status.HTTP_403_FORBIDDEN)

    refresh = RefreshToken.for_user(user)
    return Response({
        'refresh': str(refresh),
        'access': str(refresh.access_token),
        'role': user.role,
        'user_id': user.pk
    })


@extend_schema(
    summary="Generate Officer Invite Link",
    request=inline_serializer(
        name='InviteOfficerSerializer',
        fields={'email': serializers.EmailField()}
    )
)
@api_view(['POST'])
@permission_classes([IsSupervisor | IsSuperAdmin])  # <--- Allows both!
def generate_invite_link(request):
    token = signer.sign(f"supervisor:{request.user.pk}")
    invite_url = f"https://yourapp.com/register?token={token}"
    return Response({'invite_token': token, 'invite_url': invite_url})


@extend_schema(
    summary="Register Officer",
    description="Officer registers using invite token received from Supervisor",
    request=RegisterOfficerSerializer,  # <--- Shows JSON body in Swagger
    parameters=[
        OpenApiParameter(
            name='token',
            type=str,
            location=OpenApiParameter.QUERY,
            required=True,
            description='Invite token generated by Supervisor'
        )
    ]
)
@api_view(['POST'])
@permission_classes([permissions.AllowAny])
def register_officer(request):
    token = request.query_params.get('token')
    if not token:
        return Response({'error': 'Invite token is required'}, status=status.HTTP_400_BAD_REQUEST)
    
    try:
        unsigned_data = signer.unsign(token, max_age=172800)
        supervisor_id = unsigned_data.split(':')[1]
    except (BadSignature, SignatureExpired):
        return Response({'error': 'Invalid or expired invite token'}, status=status.HTTP_400_BAD_REQUEST)

    email = request.data.get('email')
    password = request.data.get('password')
    name = request.data.get('name')
    phone = request.data.get('phone')

    if User.objects.filter(email=email).exists():
        return Response({'error': 'Email already exists'}, status=status.HTTP_400_BAD_REQUEST)

    supervisor = User.objects.get(pk=supervisor_id)
    user = User.objects.create_user(
        email=email,
        password=password,
        name=name,
        phone=phone,
        role=User.Role.OFFICER,
        status=User.Status.PENDING,
        supervisor=supervisor
    )
    return Response({'message': 'Officer registered successfully. Pending approval.'}, status=status.HTTP_201_CREATED)


# ==========================================
# 2. USER MANAGEMENT MODULE (4 APIs)
# ==========================================

@extend_schema(
    summary="Create Supervisor",
    description="Create a new supervisor user account.",
    request=inline_serializer(
        name='CreateSupervisorSerializer',
        fields={
            'username': serializers.CharField(),
            'email': serializers.EmailField(),
            'password': serializers.CharField(write_only=True),
            'first_name': serializers.CharField(required=False),
            'last_name': serializers.CharField(required=False),
        }
    ),
    responses={
        201: inline_serializer(
            name='CreateSupervisorSuccess',
            fields={
                'id': serializers.IntegerField(),
                'username': serializers.CharField(),
                'email': serializers.EmailField(),
                'message': serializers.CharField()
            }
        ),
        400: inline_serializer('SupervisorErrorResponse', fields={'error': serializers.CharField()})
    }
)
@api_view(['POST'])
@permission_classes([IsSuperAdmin])
def create_supervisor(request):
    email = request.data.get('email')
    password = request.data.get('password')
    name = request.data.get('name')
    phone = request.data.get('phone')

    if User.objects.filter(email=email).exists():
        return Response({'error': 'Email already exists'}, status=status.HTTP_400_BAD_REQUEST)

    user = User.objects.create_user(
        email=email,
        password=password,
        name=name,
        phone=phone,
        role=User.Role.SUPERVISOR,
        status=User.Status.ACTIVE
    )
    return Response(UserSerializer(user).data, status=status.HTTP_201_CREATED)


class UserListView(generics.ListAPIView):
    """GET /api/users - Super Admin views all users"""
    serializer_class = UserSerializer
    permission_classes = [IsSuperAdmin]
    queryset = User.objects.all()


class SupervisorOfficerListView(generics.ListAPIView):
    """GET /api/officers - Supervisor views assigned officers"""
    serializer_class = UserSerializer
    permission_classes = [IsSupervisor]

    def get_queryset(self):
        return User.objects.filter(supervisor=self.request.user, role=User.Role.OFFICER)


@extend_schema(
    summary="Approve or Reject Officer Registration",
    description="Supervisor approves or rejects an officer's pending registration.",
    request=inline_serializer(
        name='OfficerDecisionRequest',
        fields={
            'action': serializers.ChoiceField(choices=['approve', 'reject'], help_text="Action to take: 'approve' or 'reject'")
        }
    )
)
@api_view(['POST'])
@permission_classes([IsSupervisor])
def decide_officer_registration(request, officer_id):
    officer = get_object_or_404(User, pk=officer_id, supervisor=request.user)
    action = request.data.get('action') # 'approve' or 'reject'
    
    if action == 'approve':
        officer.status = User.Status.ACTIVE
    elif action == 'reject':
        officer.status = User.Status.REJECTED
    else:
        return Response({'error': 'Invalid action. Use "approve" or "reject"'}, status=status.HTTP_400_BAD_REQUEST)
    
    officer.save()
    return Response({'message': f'Officer registration status updated to {officer.status}'})


# ==========================================
# 3. SHIFT & GEO-FENCING MODULE (5 APIs)
# ==========================================
@extend_schema(
    summary="Create a new shift",
    description="Supervisor or Super Admin creates a new duty shift.",
    request=ShiftSerializer,
    responses={201: ShiftSerializer}
)
class ShiftListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/shifts - Create shifts (Supervisor) or view available shifts"""
    serializer_class = ShiftSerializer

    def get_permissions(self):
        if self.request.method == 'POST':
            return [IsSupervisor()]
        return [permissions.IsAuthenticated()]

    def get_queryset(self):
        user = cast(User, self.request.user)

        if user.role == User.Role.SUPERVISOR:
            return Shift.objects.filter(supervisor=user)

        return Shift.objects.all()

    def perform_create(self, serializer):
        serializer.save(supervisor=self.request.user)


@extend_schema(summary="Apply for Shift", description="Officer applies for an available shift")
@api_view(['POST'])
@permission_classes([IsOfficer])
def apply_shift(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    existing = ShiftApplication.objects.filter(shift=shift, officer=request.user).first()
    
    if existing:
        return Response({'error': 'Already applied for this shift'}, status=status.HTTP_400_BAD_REQUEST)

    app = ShiftApplication.objects.create(shift=shift, officer=request.user)
    return Response(ShiftApplicationSerializer(app).data, status=status.HTTP_201_CREATED)


@extend_schema(
    summary="Approve or Reject Shift Application",
    description="Supervisor approves or rejects an officer's shift application.",
    request=inline_serializer(
        name='ShiftApplicationDecisionRequest',
        fields={
            'status': serializers.ChoiceField(
                choices=['APPROVED', 'REJECTED'],  # or ['approve', 'reject'] based on your view logic
                help_text="Decision status: 'APPROVED' or 'REJECTED'"
            )
        }
    )
)
@api_view(['POST'])
@permission_classes([IsSupervisor])
def decide_shift_application(request, application_id):
    app = get_object_or_404(ShiftApplication, pk=application_id, shift__supervisor=request.user)
    decision = request.data.get('decision') # 'accepted' or 'rejected'

    if decision not in [ShiftApplication.Status.ACCEPTED, ShiftApplication.Status.REJECTED]:
        return Response({'error': 'Invalid decision'}, status=status.HTTP_400_BAD_REQUEST)

    app.status = decision
    app.save()
    return Response({'message': f'Shift application updated to {decision}'})


# Define the location schema reusable across check-in and check-out
LocationSerializer = inline_serializer(
    name='LocationCoordinatesRequest',
    fields={
        'latitude': serializers.FloatField(help_text="Current GPS latitude coordinate"),
        'longitude': serializers.FloatField(help_text="Current GPS longitude coordinate"),
    }
)


@extend_schema(
    summary="Officer Shift Check-In",
    description="Check in to an assigned shift using GPS location (must be within shift radius).",
    request=LocationSerializer,
    responses={
        200: inline_serializer(
            name='CheckInSuccessResponse',
            fields={
                'message': serializers.CharField(),
                'distance_meters': serializers.FloatField()
            }
        ),
        400: inline_serializer(
            name='CheckInErrorResponse',
            fields={'error': serializers.CharField()}
        )
    }
)
@api_view(['POST'])
@permission_classes([IsOfficer])
def checkin_shift(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)

    # -------------------------------------------------------------------
    # 🔴 PREVENT DOUBLE CHECK-IN: Check the officer's latest shift log
    # -------------------------------------------------------------------
    latest_log = ShiftLog.objects.filter(
        shift=shift, 
        officer=request.user
    ).order_by('-created_at').first()

    if latest_log and latest_log.type == ShiftLog.Type.CHECKIN:
        return Response(
            {'error': 'You are already checked in to this shift. Please check out first.'},
            status=status.HTTP_400_BAD_REQUEST
        )

    lat = request.data.get('latitude')
    lng = request.data.get('longitude')

    if lat is None or lng is None:
        return Response({'error': 'Both latitude and longitude are required.'}, status=status.HTTP_400_BAD_REQUEST)

    try:
        officer_lat = float(lat)
        officer_lng = float(lng)
    except ValueError:
        return Response({'error': 'Latitude and longitude must be valid numbers.'}, status=status.HTTP_400_BAD_REQUEST)

    distance = calculate_haversine_distance(officer_lat, officer_lng, shift.latitude, shift.longitude)

    # Use 5.0 meters strictly, or shift.radius_meters if explicitly set smaller
    allowed_radius = min(getattr(shift, 'radius_meters', 5.0) or 5.0, 5.0)

    if distance > allowed_radius:
        return Response({
            'error': f'You are outside the shift location. Distance: {round(distance, 2)}m (Max allowed: {allowed_radius}m)'
        }, status=status.HTTP_400_BAD_REQUEST)

    ShiftLog.objects.create(
        shift=shift, 
        officer=request.user,
        type=ShiftLog.Type.CHECKIN, 
        latitude=officer_lat, 
        longitude=officer_lng, 
        within_boundary=True
    )
    return Response({'message': 'Check-in successful', 'distance_meters': round(distance, 2)})


@extend_schema(
    summary="Officer Shift Check-Out",
    description="Check out of an active shift using GPS location (must be within shift radius).",
    request=LocationSerializer,
    responses={
        200: inline_serializer(
            name='CheckOutSuccessResponse',
            fields={
                'message': serializers.CharField(),
                'distance_meters': serializers.FloatField()
            }
        ),
        400: inline_serializer(
            name='CheckOutErrorResponse',
            fields={'error': serializers.CharField()}
        )
    }
)
@api_view(['POST'])
@permission_classes([IsOfficer])
def checkout_shift(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)

    has_checked_in = ShiftLog.objects.filter(
        shift=shift, 
        officer=request.user, 
        type=ShiftLog.Type.CHECKIN
    ).exists()

    if not has_checked_in:
        return Response(
            {'error': 'You cannot check out without checking in first.'}, 
            status=status.HTTP_400_BAD_REQUEST
        )

    lat = request.data.get('latitude')
    lng = request.data.get('longitude')

    # 1. Validate that coordinates were provided
    if lat is None or lng is None:
        return Response(
            {'error': 'Both latitude and longitude are required.'}, 
            status=status.HTTP_400_BAD_REQUEST
        )

    # 2. Convert coordinates to float safely
    try:
        officer_lat = float(lat)
        officer_lng = float(lng)
    except ValueError:
        return Response(
            {'error': 'Latitude and longitude must be valid numbers.'}, 
            status=status.HTTP_400_BAD_REQUEST
        )

    # 3. Calculate Haversine distance in meters
    distance = calculate_haversine_distance(officer_lat, officer_lng, shift.latitude, shift.longitude)

    # 4. Enforce strict 5.0 meter geofence boundary cap
    allowed_radius = min(getattr(shift, 'radius_meters', 5.0) or 5.0, 5.0)

    if distance > allowed_radius:
        return Response(
            {'error': f'You are outside the shift location. Distance: {round(distance, 2)}m (Max allowed: {allowed_radius}m)'},
            status=status.HTTP_400_BAD_REQUEST
        )

    # 5. Log the Check-Out event
    ShiftLog.objects.create(
        shift=shift,
        officer=request.user,
        type=ShiftLog.Type.CHECKOUT,
        latitude=officer_lat,
        longitude=officer_lng,
        within_boundary=True
    )

    return Response({
        'message': 'Check-out successful',
        'distance_meters': round(distance, 2)
    }, status=status.HTTP_200_OK)


# ==========================================
# 4. COMMUNICATION & INCIDENTS MODULE (4 APIs)
# ==========================================

@extend_schema(
    summary="Send Direct Message",
    request=inline_serializer(
        name='DirectMessageSerializer',
        fields={
            'recipient': serializers.IntegerField(help_text="User ID of the receiver"),
            'content': serializers.CharField(help_text="Message body text")
        }
    ),
    responses={201: inline_serializer('DirectMessageSuccess', fields={'message': serializers.CharField()})}
)
@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def send_message(request):
    sender = request.user
    content = request.data.get('message')

    if sender.role == User.Role.OFFICER:
        msg = Message.objects.create(
            sender=sender, receiver=sender.supervisor, supervisor=sender.supervisor,
            message=content, is_broadcast=False
        )
    else:
        receiver_id = request.data.get('receiver_id')
        receiver = get_object_or_404(User, pk=receiver_id, supervisor=sender)
        msg = Message.objects.create(
            sender=sender, receiver=receiver, supervisor=sender,
            message=content, is_broadcast=False
        )
    return Response(MessageSerializer(msg).data, status=status.HTTP_201_CREATED)


@extend_schema(
    summary="Broadcast Message",
    request=inline_serializer(
        name='BroadcastMessageSerializer',
        fields={
            'title': serializers.CharField(required=False, default="Notice"),
            'content': serializers.CharField(help_text="Message to broadcast to all officers"),
            'target_role': serializers.CharField(required=False, help_text="e.g. OFFICER or ALL")
        }
    ),
    responses={201: inline_serializer('BroadcastSuccess', fields={'message': serializers.CharField()})}
)
@api_view(['POST'])
@permission_classes([IsSupervisor])
def broadcast_message(request):
    content = request.data.get('message')
    msg = Message.objects.create(
        sender=request.user, receiver=None, supervisor=request.user,
        message=content, is_broadcast=True
    )
    return Response({'message': 'Broadcast sent successfully', 'id': msg.pk}, status=status.HTTP_201_CREATED)


class IncidentListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/incidents - Report or view shift incidents"""
    serializer_class = IncidentSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = cast(User, self.request.user)

        if user.role == User.Role.SUPER_ADMIN:
            return Incident.objects.all()
        elif user.role == User.Role.SUPERVISOR:
            return Incident.objects.filter(officer__supervisor=user)

        return Incident.objects.filter(officer=user)

    def perform_create(self, serializer):
        serializer.save(officer=self.request.user)


class ReportListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/reports - Submit or view shift reports"""
    serializer_class = ReportSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = cast(User, self.request.user)

        if user.role == User.Role.SUPER_ADMIN:
            return Report.objects.all()
        elif user.role == User.Role.SUPERVISOR:
            return Report.objects.filter(officer__supervisor=user)

        return Report.objects.filter(officer=user)

    def perform_create(self, serializer):
        serializer.save(officer=self.request.user)

# ==========================================
# 5. TRACKING MODULE (2 APIs)
# ==========================================

@extend_schema(
    summary="Update Live Location",
    request=inline_serializer(
        name='LocationUpdateSerializer',
        fields={
            'latitude': serializers.FloatField(),
            'longitude': serializers.FloatField(),
        }
    ),
    responses={200: inline_serializer('LocationUpdateSuccess', fields={'message': serializers.CharField()})}
)
@api_view(['POST'])
@permission_classes([IsOfficer])
def update_location(request):
    lat = float(request.data.get('latitude'))
    lng = float(request.data.get('longitude'))
    
    LiveLocation.objects.update_or_create(
        officer=request.user,
        defaults={'latitude': lat, 'longitude': lng}
    )
    return Response({'status': 'Location updated'})


@extend_schema(summary="Get Officer Location", description="Supervisor fetches live location of assigned officer")
@api_view(['GET'])
@permission_classes([IsSupervisor])
def get_officer_location(request, officer_id):
    officer = get_object_or_404(User, pk=officer_id, supervisor=request.user)
    location = get_object_or_404(LiveLocation, officer=officer)
    
    return Response({
        'officer_id': officer.pk,
        'latitude': location.latitude,
        'longitude': location.longitude,
        'updated_at': location.updated_at
    })

# --- DOCUMENT COMPLIANCE & EXPIRY VIEWS ---

class DocumentListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/documents - Upload document or view officer documents"""
    serializer_class = DocumentSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = cast(User, self.request.user)
        if user.role == User.Role.SUPER_ADMIN:
            return Document.objects.all()
        elif user.role == User.Role.SUPERVISOR:
            return Document.objects.filter(officer__supervisor=user)
        return Document.objects.filter(officer=user)

    def perform_create(self, serializer):
        user = cast(User, self.request.user)
        
        # Check if request.data is a dict before calling .get()
        signature = None
        if isinstance(self.request.data, dict):
            signature = self.request.data.get('digital_signature')

        serializer.save(
            officer=user,
            digital_signature=signature,
            signed_at=timezone.now() if signature else None
        )


@extend_schema(summary="Expiring Documents Alert", description="Get list of documents expiring within 30 days")
@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def expiring_documents(request):
    user = cast(User, request.user)
    threshold = timezone.now().date() + timedelta(days=30)
    
    if user.role == User.Role.SUPERVISOR:
        docs = Document.objects.filter(officer__supervisor=user, expiry_date__lte=threshold)
    else:
        docs = Document.objects.filter(officer=user, expiry_date__lte=threshold)

    return Response(DocumentSerializer(docs, many=True).data)


# --- INVOICING VIEWS ---

class InvoiceListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/invoices - Generate or view staff invoices"""
    serializer_class = InvoiceSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = cast(User, self.request.user)
        if user.role == User.Role.SUPER_ADMIN:
            return Invoice.objects.all()
        elif user.role == User.Role.SUPERVISOR:
            return Invoice.objects.filter(officer__supervisor=user)
        return Invoice.objects.filter(officer=user)

    def perform_create(self, serializer):
        user = cast(User, self.request.user)
        hours = serializer.validated_data.get('hours_worked', 0)
        rate = serializer.validated_data.get('hourly_rate', 0)
        total = hours * rate
        inv_num = f"INV-{uuid.uuid4().hex[:8].upper()}"

        serializer.save(
            officer=user,
            company=user.company,
            total_amount=total,
            invoice_number=inv_num
        )