# core/views.py
from rest_framework import status, permissions, generics
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken
from django.shortcuts import get_object_or_404
from django.core.signing import TimestampSigner, BadSignature, SignatureExpired
from drf_spectacular.utils import extend_schema, OpenApiParameter

from .models import User, Shift, ShiftApplication, ShiftLog, LiveLocation, Incident, Report, Message
from .serializers import (
    UserSerializer, ShiftSerializer, ShiftApplicationSerializer,
    IncidentSerializer, ReportSerializer, MessageSerializer, LoginSerializer, RegisterOfficerSerializer
)
from .permissions import IsSuperAdmin, IsSupervisor, IsOfficer
from .utils import calculate_haversine_distance
from typing import cast
from .models import User

signer = TimestampSigner()

# ==========================================
# 1. AUTHENTICATION MODULE (3 APIs)
# ==========================================

@extend_schema(
    summary="User Login",
    description="Authenticate any user and return JWT tokens",
    request=LoginSerializer,  # <--- Tells Swagger to display email & password fields!
)
@api_view(['POST'])
@permission_classes([permissions.AllowAny])
def login_view(request):
    email = request.data.get('email')
    password = request.data.get('password')

    user = User.objects.filter(email=email).first()
    if not user or not user.check_password(password):
        return Response({'error': 'Invalid credentials'}, status=status.HTTP_401_UNAUTHORIZED)

    if user.status != User.Status.ACTIVE:
        return Response({'error': f'Account is {user.status}. Access denied.'}, status=status.HTTP_403_FORBIDDEN)

    refresh = RefreshToken.for_user(user)
    return Response({
        'refresh': str(refresh),
        'access': str(refresh.access_token),
        'role': user.role,
        'user_id': user.pk
    })


@extend_schema(summary="Generate Officer Invite Link", description="Supervisor generates invitation token for officer registration")
@api_view(['POST'])
@permission_classes([IsSupervisor])
def generate_invite_link(request):
    token = signer.sign(f"supervisor:{request.user.pk}")
    invite_url = f"https://yourapp.com/register?token={token}"
    return Response({'invite_token': token, 'invite_url': invite_url})


@extend_schema(
    summary="Register Officer",
    description="Officer registers using invite token received from Supervisor",
    request=RegisterOfficerSerializer,  # <--- Shows JSON body in Swagger
    parameters=[
        OpenApiParameter(
            name='token',
            type=str,
            location=OpenApiParameter.QUERY,
            required=True,
            description='Invite token generated by Supervisor'
        )
    ]
)
@api_view(['POST'])
@permission_classes([permissions.AllowAny])
def register_officer(request):
    token = request.query_params.get('token')
    if not token:
        return Response({'error': 'Invite token is required'}, status=status.HTTP_400_BAD_REQUEST)
    
    try:
        unsigned_data = signer.unsign(token, max_age=172800)
        supervisor_id = unsigned_data.split(':')[1]
    except (BadSignature, SignatureExpired):
        return Response({'error': 'Invalid or expired invite token'}, status=status.HTTP_400_BAD_REQUEST)

    email = request.data.get('email')
    password = request.data.get('password')
    name = request.data.get('name')
    phone = request.data.get('phone')

    if User.objects.filter(email=email).exists():
        return Response({'error': 'Email already exists'}, status=status.HTTP_400_BAD_REQUEST)

    supervisor = User.objects.get(pk=supervisor_id)
    user = User.objects.create_user(
        email=email,
        password=password,
        name=name,
        phone=phone,
        role=User.Role.OFFICER,
        status=User.Status.PENDING,
        supervisor=supervisor
    )
    return Response({'message': 'Officer registered successfully. Pending approval.'}, status=status.HTTP_201_CREATED)


# ==========================================
# 2. USER MANAGEMENT MODULE (4 APIs)
# ==========================================

@extend_schema(summary="Create Supervisor", description="Super Admin creates a new supervisor account")
@api_view(['POST'])
@permission_classes([IsSuperAdmin])
def create_supervisor(request):
    email = request.data.get('email')
    password = request.data.get('password')
    name = request.data.get('name')
    phone = request.data.get('phone')

    if User.objects.filter(email=email).exists():
        return Response({'error': 'Email already exists'}, status=status.HTTP_400_BAD_REQUEST)

    user = User.objects.create_user(
        email=email,
        password=password,
        name=name,
        phone=phone,
        role=User.Role.SUPERVISOR,
        status=User.Status.ACTIVE
    )
    return Response(UserSerializer(user).data, status=status.HTTP_201_CREATED)


class UserListView(generics.ListAPIView):
    """GET /api/users - Super Admin views all users"""
    serializer_class = UserSerializer
    permission_classes = [IsSuperAdmin]
    queryset = User.objects.all()


class SupervisorOfficerListView(generics.ListAPIView):
    """GET /api/officers - Supervisor views assigned officers"""
    serializer_class = UserSerializer
    permission_classes = [IsSupervisor]

    def get_queryset(self):
        return User.objects.filter(supervisor=self.request.user, role=User.Role.OFFICER)


@extend_schema(summary="Approve/Reject Officer Registration", description="Supervisor decides officer pending registration")
@api_view(['POST'])
@permission_classes([IsSupervisor])
def decide_officer_registration(request, officer_id):
    officer = get_object_or_404(User, pk=officer_id, supervisor=request.user)
    action = request.data.get('action') # 'approve' or 'reject'
    
    if action == 'approve':
        officer.status = User.Status.ACTIVE
    elif action == 'reject':
        officer.status = User.Status.REJECTED
    else:
        return Response({'error': 'Invalid action. Use "approve" or "reject"'}, status=status.HTTP_400_BAD_REQUEST)
    
    officer.save()
    return Response({'message': f'Officer registration status updated to {officer.status}'})


# ==========================================
# 3. SHIFT & GEO-FENCING MODULE (5 APIs)
# ==========================================

class ShiftListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/shifts - Create shifts (Supervisor) or view available shifts"""
    serializer_class = ShiftSerializer

    def get_permissions(self):
        if self.request.method == 'POST':
            return [IsSupervisor()]
        return [permissions.IsAuthenticated()]

    def get_queryset(self):
        user = cast(User, self.request.user)

        if user.role == User.Role.SUPERVISOR:
            return Shift.objects.filter(supervisor=user)

        return Shift.objects.all()

    def perform_create(self, serializer):
        serializer.save(supervisor=self.request.user)


@extend_schema(summary="Apply for Shift", description="Officer applies for an available shift")
@api_view(['POST'])
@permission_classes([IsOfficer])
def apply_shift(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    existing = ShiftApplication.objects.filter(shift=shift, officer=request.user).first()
    
    if existing:
        return Response({'error': 'Already applied for this shift'}, status=status.HTTP_400_BAD_REQUEST)

    app = ShiftApplication.objects.create(shift=shift, officer=request.user)
    return Response(ShiftApplicationSerializer(app).data, status=status.HTTP_201_CREATED)


@extend_schema(summary="Accept/Reject Shift Application", description="Supervisor decides an officer shift application")
@api_view(['POST'])
@permission_classes([IsSupervisor])
def decide_shift_application(request, application_id):
    app = get_object_or_404(ShiftApplication, pk=application_id, shift__supervisor=request.user)
    decision = request.data.get('decision') # 'accepted' or 'rejected'

    if decision not in [ShiftApplication.Status.ACCEPTED, ShiftApplication.Status.REJECTED]:
        return Response({'error': 'Invalid decision'}, status=status.HTTP_400_BAD_REQUEST)

    app.status = decision
    app.save()
    return Response({'message': f'Shift application updated to {decision}'})


@extend_schema(summary="Shift Check-in", description="Officer check-in with 100m radius geo-fencing check")
@api_view(['POST'])
@permission_classes([IsOfficer])
def checkin_shift(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    officer_lat = float(request.data.get('latitude'))
    officer_lng = float(request.data.get('longitude'))

    distance = calculate_haversine_distance(officer_lat, officer_lng, shift.latitude, shift.longitude)

    if distance > shift.radius_meters:
        return Response({'error': f'You are outside the shift location. Distance: {round(distance, 2)}m'}, status=status.HTTP_400_BAD_REQUEST)

    ShiftLog.objects.create(
        shift=shift, officer=request.user,
        type=ShiftLog.Type.CHECKIN, latitude=officer_lat, longitude=officer_lng, within_boundary=True
    )
    return Response({'message': 'Check-in successful', 'distance_meters': round(distance, 2)})


@extend_schema(summary="Shift Check-out", description="Officer check-out with 100m radius geo-fencing check")
@api_view(['POST'])
@permission_classes([IsOfficer])
def checkout_shift(request, shift_id):
    shift = get_object_or_404(Shift, pk=shift_id)
    officer_lat = float(request.data.get('latitude'))
    officer_lng = float(request.data.get('longitude'))

    distance = calculate_haversine_distance(officer_lat, officer_lng, shift.latitude, shift.longitude)

    if distance > shift.radius_meters:
        return Response({'error': f'You are outside the shift location. Distance: {round(distance, 2)}m'}, status=status.HTTP_400_BAD_REQUEST)

    ShiftLog.objects.create(
        shift=shift, officer=request.user,
        type=ShiftLog.Type.CHECKOUT, latitude=officer_lat, longitude=officer_lng, within_boundary=True
    )
    return Response({'message': 'Check-out successful', 'distance_meters': round(distance, 2)})


# ==========================================
# 4. COMMUNICATION & INCIDENTS MODULE (4 APIs)
# ==========================================

@extend_schema(summary="Send Direct Message", description="Send 1-on-1 message between officer and supervisor")
@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def send_message(request):
    sender = request.user
    content = request.data.get('message')

    if sender.role == User.Role.OFFICER:
        msg = Message.objects.create(
            sender=sender, receiver=sender.supervisor, supervisor=sender.supervisor,
            message=content, is_broadcast=False
        )
    else:
        receiver_id = request.data.get('receiver_id')
        receiver = get_object_or_404(User, pk=receiver_id, supervisor=sender)
        msg = Message.objects.create(
            sender=sender, receiver=receiver, supervisor=sender,
            message=content, is_broadcast=False
        )
    return Response(MessageSerializer(msg).data, status=status.HTTP_201_CREATED)


@extend_schema(summary="Broadcast Message", description="Supervisor sends broadcast message to all assigned officers")
@api_view(['POST'])
@permission_classes([IsSupervisor])
def broadcast_message(request):
    content = request.data.get('message')
    msg = Message.objects.create(
        sender=request.user, receiver=None, supervisor=request.user,
        message=content, is_broadcast=True
    )
    return Response({'message': 'Broadcast sent successfully', 'id': msg.pk}, status=status.HTTP_201_CREATED)


class IncidentListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/incidents - Report or view shift incidents"""
    serializer_class = IncidentSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = cast(User, self.request.user)

        if user.role == User.Role.SUPER_ADMIN:
            return Incident.objects.all()
        elif user.role == User.Role.SUPERVISOR:
            return Incident.objects.filter(officer__supervisor=user)

        return Incident.objects.filter(officer=user)

    def perform_create(self, serializer):
        serializer.save(officer=self.request.user)


class ReportListCreateView(generics.ListCreateAPIView):
    """GET/POST /api/reports - Submit or view shift reports"""
    serializer_class = ReportSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = cast(User, self.request.user)

        if user.role == User.Role.SUPER_ADMIN:
            return Report.objects.all()
        elif user.role == User.Role.SUPERVISOR:
            return Report.objects.filter(officer__supervisor=user)

        return Report.objects.filter(officer=user)

    def perform_create(self, serializer):
        serializer.save(officer=self.request.user)

# ==========================================
# 5. TRACKING MODULE (2 APIs)
# ==========================================

@extend_schema(summary="Update Live Location", description="Officer sends live GPS coordinates during shift")
@api_view(['POST'])
@permission_classes([IsOfficer])
def update_location(request):
    lat = float(request.data.get('latitude'))
    lng = float(request.data.get('longitude'))
    
    LiveLocation.objects.update_or_create(
        officer=request.user,
        defaults={'latitude': lat, 'longitude': lng}
    )
    return Response({'status': 'Location updated'})


@extend_schema(summary="Get Officer Location", description="Supervisor fetches live location of assigned officer")
@api_view(['GET'])
@permission_classes([IsSupervisor])
def get_officer_location(request, officer_id):
    officer = get_object_or_404(User, pk=officer_id, supervisor=request.user)
    location = get_object_or_404(LiveLocation, officer=officer)
    
    return Response({
        'officer_id': officer.pk,
        'latitude': location.latitude,
        'longitude': location.longitude,
        'updated_at': location.updated_at
    })